import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { z } from "zod";
import { ConstraintType, ConstraintWeight } from "@prisma/client";
import { authOptions } from "@/lib/auth";
import { hasAnyRole } from "@/lib/org-roles";
import { authorizeScheduleAccess, canEditScheduleAssignments } from "@/lib/schedule-access";
import { prisma } from "@/lib/prisma";

type Params = { params: Promise<{ scheduleId: string }> };

function isDateInSchedule(date: string, schedule: { year: number; month: number; generationLog: unknown }) {
  const meta = (schedule.generationLog ?? {}) as { startDate?: string; endDate?: string };
  if (meta.startDate && meta.endDate) return date >= meta.startDate && date <= meta.endDate;
  const d = new Date(`${date}T00:00:00.000Z`);
  return d.getUTCFullYear() === schedule.year && d.getUTCMonth() + 1 === schedule.month;
}

const exportedAssignmentSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  shiftTypeId: z.string().min(1),
  memberId: z.string().min(1).optional().nullable(),
  guestLabel: z.string().max(120).optional().nullable(),
  guestColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional().nullable(),
  isAutoGenerated: z.boolean().optional(),
});

const exportedMonthlySchema = z.object({
  memberId: z.string().min(1),
  type: z.nativeEnum(ConstraintType),
  weight: z.nativeEnum(ConstraintWeight).optional(),
  value: z.unknown(),
  note: z.string().nullable().optional(),
});

const bundleSchema = z.object({
  version: z.literal(1),
  calendarId: z.string().min(1),
  scheduleId: z.string().optional(),
  assignments: z.array(exportedAssignmentSchema),
  monthlyConstraints: z.array(exportedMonthlySchema),
  scheduleRules: z.unknown().optional(),
  calendarRules: z.unknown().optional(),
});

export async function GET(_: Request, { params }: Params) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return NextResponse.json({ error: "Non autenticato" }, { status: 401 });

  const { scheduleId } = await params;
  const access = await authorizeScheduleAccess(scheduleId, session.user.id);
  if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status });
  if (!hasAnyRole(access.roles, ["OWNER", "ADMIN", "MANAGER"])) {
    return NextResponse.json({ error: "Permessi insufficienti" }, { status: 403 });
  }

  const schedule = await prisma.schedule.findUnique({
    where: { id: scheduleId },
    select: {
      id: true,
      calendarId: true,
      year: true,
      month: true,
      generationLog: true,
      rules: true,
      calendar: { select: { name: true, rules: true } },
    },
  });
  if (!schedule) return NextResponse.json({ error: "Turno non trovato" }, { status: 404 });

  const [assignments, monthlyConstraints] = await Promise.all([
    prisma.shiftAssignment.findMany({
      where: { scheduleId },
      select: {
        date: true,
        shiftTypeId: true,
        memberId: true,
        guestLabel: true,
        guestColor: true,
        isAutoGenerated: true,
      },
      orderBy: [{ date: "asc" }, { createdAt: "asc" }],
    }),
    prisma.monthlyConstraint.findMany({
      where: { scheduleId },
      select: { memberId: true, type: true, weight: true, value: true, note: true },
      orderBy: [{ memberId: "asc" }, { createdAt: "asc" }],
    }),
  ]);

  const meta = (schedule.generationLog ?? {}) as { startDate?: string; endDate?: string; periodType?: string };

  return NextResponse.json({
    version: 1 as const,
    exportedAt: new Date().toISOString(),
    calendarId: schedule.calendarId,
    scheduleId: schedule.id,
    calendarName: schedule.calendar.name,
    period: {
      year: schedule.year,
      month: schedule.month,
      startDate: meta.startDate,
      endDate: meta.endDate,
      periodType: meta.periodType,
    },
    assignments: assignments.map((a) => ({
      date: a.date.toISOString().slice(0, 10),
      shiftTypeId: a.shiftTypeId,
      memberId: a.memberId,
      guestLabel: a.guestLabel,
      guestColor: a.guestColor,
      isAutoGenerated: a.isAutoGenerated,
    })),
    monthlyConstraints,
    scheduleRules: schedule.rules ?? undefined,
    calendarRules: schedule.calendar.rules ?? undefined,
  });
}

export async function POST(req: Request, { params }: Params) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return NextResponse.json({ error: "Non autenticato" }, { status: 401 });

  const { scheduleId } = await params;
  const access = await authorizeScheduleAccess(scheduleId, session.user.id);
  if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status });
  if (!canEditScheduleAssignments(access.roles, access.schedule.status)) {
    return NextResponse.json({ error: "Import consentito solo in bozza, con ruolo responsabile" }, { status: 403 });
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Body non valido" }, { status: 400 });
  }

  const wrapSchema = z.object({
    confirmReplace: z.literal(true),
    replaceCalendarRules: z.boolean().optional(),
    bundle: z.unknown(),
  });
  const parsedWrap = wrapSchema.safeParse(body);
  if (!parsedWrap.success) {
    return NextResponse.json(
      { error: "Richiesta non valida: serve confirmReplace: true e bundle" },
      { status: 400 },
    );
  }

  const parsedBundle = bundleSchema.safeParse(parsedWrap.data.bundle);
  if (!parsedBundle.success) {
    return NextResponse.json(
      { error: "File configurazione non valido o versione non supportata" },
      { status: 400 },
    );
  }

  const bundle = parsedBundle.data;
  if (bundle.calendarId !== access.schedule.calendarId) {
    return NextResponse.json(
      { error: "Il file è di un altro calendario: import possibile solo sullo stesso calendario." },
      { status: 400 },
    );
  }

  const shiftTypeIds = new Set(
    (await prisma.shiftType.findMany({
      where: { calendarId: access.schedule.calendarId },
      select: { id: true },
    })).map((s) => s.id),
  );

  const memberIds = new Set(
    (await prisma.calendarMember.findMany({
      where: { calendarId: access.schedule.calendarId, isActive: true },
      select: { id: true },
    })).map((m) => m.id),
  );

  for (const a of bundle.assignments) {
    if (!isDateInSchedule(a.date, access.schedule)) {
      return NextResponse.json({ error: `Data fuori periodo: ${a.date}` }, { status: 400 });
    }
    if (!shiftTypeIds.has(a.shiftTypeId)) {
      return NextResponse.json({ error: `Tipo turno non valido nel calendario: ${a.shiftTypeId}` }, { status: 400 });
    }
    const hasMember = a.memberId && String(a.memberId).length > 0;
    const hasGuest = (a.guestLabel ?? "").trim().length > 0;
    if (hasMember === hasGuest) {
      return NextResponse.json(
        { error: "Ogni assegnazione deve avere un membro oppure un nome persona extra" },
        { status: 400 },
      );
    }
    if (hasMember && !memberIds.has(String(a.memberId))) {
      return NextResponse.json({ error: `Membro calendario non valido: ${a.memberId}` }, { status: 400 });
    }
  }

  for (const c of bundle.monthlyConstraints) {
    if (!memberIds.has(c.memberId)) {
      return NextResponse.json({ error: `Vincolo periodo: membro non valido ${c.memberId}` }, { status: 400 });
    }
    const v = c.value as { date?: string; shiftTypeId?: string };
    if (v?.date && !isDateInSchedule(v.date, access.schedule)) {
      return NextResponse.json({ error: `Vincolo: data fuori periodo (${v.date})` }, { status: 400 });
    }
    if (v?.shiftTypeId && !shiftTypeIds.has(v.shiftTypeId)) {
      return NextResponse.json({ error: "Vincolo: tipo turno non valido" }, { status: 400 });
    }
  }

  const prevRaw = access.schedule.generationLog;
  const nextLog =
    prevRaw != null && typeof prevRaw === "object" && !Array.isArray(prevRaw)
      ? { ...(prevRaw as Record<string, unknown>) }
      : {};
  nextLog.lastSolverAlerts = [];
  delete nextLog.lastAutoGenerateAt;

  const assignmentRows = bundle.assignments.map((a) => {
    const isGuest = !a.memberId || !String(a.memberId).trim();
    const d = new Date(`${a.date}T00:00:00.000Z`);
    const guestColorNorm = (a.guestColor ?? "#6b7280").trim();
    return {
      scheduleId,
      shiftTypeId: a.shiftTypeId,
      date: d,
      isAutoGenerated: a.isAutoGenerated ?? false,
      ...(isGuest
        ? {
            memberId: null as string | null,
            guestLabel: String(a.guestLabel).trim(),
            guestColor: /^#[0-9A-Fa-f]{6}$/.test(guestColorNorm) ? guestColorNorm : "#6b7280",
          }
        : {
            memberId: String(a.memberId),
            guestLabel: null as string | null,
            guestColor: null as string | null,
          }),
    };
  });

  const constraintRows = bundle.monthlyConstraints.map((c) => ({
    scheduleId,
    memberId: c.memberId,
    type: c.type,
    weight: c.weight ?? ConstraintWeight.HARD,
    value: c.value as object,
    note: c.note ?? null,
  }));

  try {
    await prisma.$transaction(async (tx) => {
      await tx.shiftAssignment.deleteMany({ where: { scheduleId } });
      await tx.monthlyConstraint.deleteMany({ where: { scheduleId } });
      if (assignmentRows.length) await tx.shiftAssignment.createMany({ data: assignmentRows });
      if (constraintRows.length) await tx.monthlyConstraint.createMany({ data: constraintRows });

      await tx.schedule.update({
        where: { id: scheduleId },
        data: {
          ...(bundle.scheduleRules !== undefined
            ? { rules: (bundle.scheduleRules ?? {}) as object }
            : {}),
          generationLog: nextLog as object,
        },
      });

      if (parsedWrap.data.replaceCalendarRules && bundle.calendarRules !== undefined) {
        await tx.calendar.update({
          where: { id: access.schedule.calendarId },
          data: { rules: (bundle.calendarRules ?? {}) as object },
        });
      }
    });

    return NextResponse.json({
      ok: true,
      imported: {
        assignments: assignmentRows.length,
        monthlyConstraints: constraintRows.length,
        scheduleRules: bundle.scheduleRules !== undefined,
        calendarRules: Boolean(parsedWrap.data.replaceCalendarRules && bundle.calendarRules !== undefined),
      },
    });
  } catch (e: unknown) {
    const code = typeof e === "object" && e !== null && "code" in e ? (e as { code: string }).code : "";
    if (code === "P2002") {
      return NextResponse.json(
        { error: "Conflitto univoco (duplicato stesso membro/data/fascia): controlla il pacchetto esportato." },
        { status: 409 },
      );
    }
    throw e;
  }
}
